// src/app/components/cavity-balance/cavity-balance.component.ts
import { Component, OnInit, ViewChild, ViewContainerRef } from '@angular/core';
import { HotColumnComponent, HotTableComponent } from '@handsontable/angular';
import { ChartDataSets, ChartOptions, ChartType } from 'chart.js';
import { Color, Label } from 'ng2-charts';

@Component({
  selector: 'app-cavity-balance',
  templateUrl: './cavity-balance.component.html',
  styleUrls: ['./cavity-balance.component.css'],
})
export class CavityBalanceComponent implements OnInit {
  @ViewChild('hot', { static: false })
  hot!: HotTableComponent;

  private noColumns: number = 3;

  dataset: any[] = [
    { weight1: 0, weight2: 0, weight3: 0 },
    { weight1: 0, weight2: 0, weight3: 0 },
    { weight1: 0, weight2: 0, weight3: 0 },
    { weight1: 0, weight2: 0, weight3: 0 },
    { weight1: 0, weight2: 0, weight3: 0 },
  ];

  public lineChartData: ChartDataSets[] = [
    { data: [0, 0, 0], label: 'Weight 1' },
    { data: [0, 0, 0], label: 'Weight 2' },
    { data: [0, 0, 0], label: 'Weight 3' },
  ];
  public lineChartLabels: Label[] = ['0'];
  public lineChartOptions: ChartOptions = {
    responsive: true,
    scales: {
      // We use this empty structure as a placeholder for dynamic theming.
      xAxes: [{}],
      yAxes: [
        {
          id: 'y-axis-0',
          position: 'left',
        },
        {
          id: 'y-axis-1',
          position: 'right',
          gridLines: {
            color: 'rgba(255,0,0,0.3)',
          },
          ticks: {
            fontColor: 'red',
          },
        },
      ],
    },
  };
  public lineChartColors: Color[] = [
    {
      // grey
      backgroundColor: 'rgba(148,159,177,0.2)',
      borderColor: 'rgba(148,159,177,1)',
      pointBackgroundColor: 'rgba(148,159,177,1)',
      pointBorderColor: '#fff',
      pointHoverBackgroundColor: '#fff',
      pointHoverBorderColor: 'rgba(148,159,177,0.8)',
    },
    {
      // dark grey
      backgroundColor: 'rgba(77,83,96,0.2)',
      borderColor: 'rgba(77,83,96,1)',
      pointBackgroundColor: 'rgba(77,83,96,1)',
      pointBorderColor: '#fff',
      pointHoverBackgroundColor: '#fff',
      pointHoverBorderColor: 'rgba(77,83,96,1)',
    },
    {
      // red
      backgroundColor: 'rgba(255,0,0,0.3)',
      borderColor: 'red',
      pointBackgroundColor: 'rgba(148,159,177,1)',
      pointBorderColor: '#fff',
      pointHoverBackgroundColor: '#fff',
      pointHoverBorderColor: 'rgba(148,159,177,0.8)',
    },
  ];
  public lineChartLegend = true;
  public lineChartType: ChartType = 'line';

  constructor() {}

  ngOnInit(): void {}

  addRow() {
    this.dataset.push(this.getRow());
    this.hot.updateHotTable({ data: this.dataset });
  }

  addRows(numberRows: number) {
    let newRow = this.getRow();
    for (var i = 0; i < numberRows; i++) {
      this.dataset.push(newRow);
    }
    this.hot.updateHotTable({ data: this.dataset });
  }

  deleteLastRow() {
    this.dataset.splice(-1, 1);
    this.hot.updateHotTable({ data: this.dataset });
  }

  deleteAllRows() {
    let row = this.getRow();
    this.dataset = [{ row }];
    this.hot.updateHotTable({ data: this.dataset });
  }

  addColumn() {
    this.noColumns++;

    this.dataset.forEach((element) => {
      element['weight' + String(this.noColumns)] = 0;
    });

    var newColumn = new HotColumnComponent(this.hot);
    newColumn.title = 'Weight ' + String(this.noColumns);
    newColumn.data = 'weight' + String(this.noColumns);

    this.hot.addColumn(newColumn);
    this.hot.updateHotTable({ data: this.dataset });
  }

  deleteColumn() {
    if (this.noColumns > 1) {
      this.dataset.forEach((element) => {
        delete element['weight' + String(this.noColumns)];
      });

      var oldColumn = new HotColumnComponent(this.hot);
      oldColumn.title = 'Weight ' + String(this.noColumns);
      oldColumn.data = 'weight' + String(this.noColumns);

      this.noColumns--;

      this.hot.removeColumn(oldColumn);
      this.hot.updateHotTable({ data: this.dataset });
    }
  }

  calculate() {
    let variationRow: any = {};

    let columnNames = Object.entries(this.dataset[0]);
    let index = 0;

    columnNames.forEach((element) => {
      let column = this.extractColumn(String(element[0]));
      index++;
      let max = Math.max(...column);
      let min = Math.min(...column);
      let variation = (max - min) / min;
      variationRow[String(element[0])] = variation.toFixed(6);
    });

    this.dataset.push(variationRow);
    this.hot.updateHotTable({ data: this.dataset });

    this.updateChart();
  }

  private getRow() {
    let columnNames = Object.entries(this.dataset[0]);
    let newRow: any = {};
    let index = 0;
    columnNames.forEach((element) => {
      newRow[columnNames[index][0]] = 0;
      index++;
    });
    return newRow;
  }

  private extractColumn(column: string) {
    return this.dataset.map((value) => +value[column]);
  }

  private updateChart() {
    this.lineChartData = [{ data: [0], label: '' }];
    this.lineChartLabels = ['0'];

    this.lineChartData.splice(-1, 1);
    this.lineChartLabels.splice(-1, 1);

    let columnNames = Object.entries(this.dataset[0]);
    let index = 1;

    columnNames.forEach((element) => {
      let columnData = this.extractColumn(String(element[0]));
      this.lineChartData.push({
        data: columnData,
        label: String(element),
      });
      index++;
      this.lineChartLabels.push(String(index));
    });
  }
}

<app-study-title name="Cavity Balance"></app-study-title>

<div class="mb-3">
  <h4>Input Data</h4>
  <div class="input-group mb-2">
    <div class="input-group-prepend">
      <span class="input-group-text">No. Rows</span>
    </div>
    <input type="number" class="form-control" placeholder="10" #noRows />
    <button
      type="button"
      class="btn btn-primary"
      (click)="addRows(+noRows.value)"
    >
      Add Rows
    </button>
    <button type="button" class="btn btn-danger" (click)="deleteAllRows()">
      Delete All Rows
    </button>
  </div>
  <div class="btn-group mx-2 mb-2" role="rows-group">
    <button type="button" class="btn btn-primary" (click)="addRow()">
      Add Row
    </button>
    <button type="button" class="btn btn-danger" (click)="deleteLastRow()">
      Delete Last Row
    </button>
  </div>
  <div class="btn-group mx-2 mb-2" role="cols-group">
    <button type="button" class="btn btn-primary" (click)="addColumn()">
      Add New Column
    </button>
    <button type="button" class="btn btn-danger" (click)="deleteColumn()">
      Delete Column
    </button>
  </div>
  <div class="wrapper">
    <hot-table
      licenseKey="non-commercial-and-evaluation"
      [colHeaders]="true"
      [rowHeaders]="true"
      [contextMenu]="true"
      [data]="dataset"
      #hot
    >
      <hot-column data="weight1" title="Weight 1"></hot-column>
      <hot-column data="weight2" title="Weight 2"></hot-column>
      <hot-column data="weight3" title="Weight 3"></hot-column>
      <!-- <hot-column data="weight4" title="Weight 4"></hot-column> -->
    </hot-table>
  </div>
</div>

<div class="mb-3">
  <div class="d-grid gap-2">
    <button type="button" class="btn btn-success" (click)="calculate()">
      Calculate
    </button>
  </div>
</div>

<div class="mb-3">
  <div class="chart-container">
    <canvas
      baseChart
      width="400"
      height="400"
      [datasets]="lineChartData"
      [labels]="lineChartLabels"
      [options]="lineChartOptions"
      [colors]="lineChartColors"
      [legend]="lineChartLegend"
      [chartType]="lineChartType"
    ></canvas>
  </div>
</div>

// src/Pages/CavityBalance/CavityBalance.jsx
import "./CavityBalance.scss";
import React from "react";
import "handsontable/dist/handsontable.min.css";
import { useState, useReducer } from "react";
import { HotTable, HotColumn } from "@handsontable/react";
import { Line } from "react-chartjs-2";

import {
  defaultChartDatasets,
  defaultDataset,
  getRandomColor,
} from "./cavitybalance-dataset";
import chartOptions from "../chartoptions";

let dataset = defaultDataset;
let chartData = {
  datasets: [],
};
// let chartLabel = ["0"];

let noColumns = 3;
let columns = [];

chartData.datasets.forEach((element) => {
  let color = getRandomColor();
  element["backgroundColor"] = color;
  element["borderColor"] = color;
});

const renderColumns = () => {
  let index = 0;
  for (const [key, value] of Object.entries(dataset[0])) {
    index++;
    columns.push(<HotColumn data={key} title={"Weight " + index} />);
  }
  chartData.datasets.push({ data: [1, 1, 1], label: "Weight 1" });
};

renderColumns();

export const CavityBalance = () => {
  const [numberOfRows, setNumberOfRows] = useState(0);
  const [, forceUpdate] = useReducer((x) => x + 1, 0);

  const updateChartColors = () => {
    chartData.datasets.forEach((element) => {
      let color = getRandomColor();
      element["backgroundColor"] = color;
      element["borderColor"] = color;
    });
  };

  const handleNumberofRows = (event) => {
    setNumberOfRows(event.target.value);
  };

  const generateNewRow = () => {
    let columnNames = Object.entries(dataset[0]);
    let newRow = {};
    let index = 0;
    columnNames.forEach((element) => {
      newRow[columnNames[index][0]] = 0;
      index++;
    });
    return newRow;
  };

  const addRow = () => {
    dataset.push(generateNewRow());
    forceUpdate();
  };

  const addRows = () => {
    let newRow = generateNewRow();
    for (var i = 0; i < numberOfRows; i++) {
      dataset.push(newRow);
    }
    forceUpdate();
  };

  const deleteLastRow = () => {
    dataset.splice(-1, 1);
    forceUpdate();
  };

  const deleteAllRows = () => {
    let row = generateNewRow();
    dataset = [{ row }];
    forceUpdate();
  };

  const addColumn = () => {
    noColumns++;

    dataset.forEach((element) => {
      element["weight" + String(noColumns)] = 0;
    });
    columns.push(
      <HotColumn
        data={"weight" + String(noColumns)}
        title={"Weight " + String(noColumns)}
      />
    );
    forceUpdate();
  };

  return (
    <div className="cavitybalance">
      <h2 className="study-title">Cavity Balance</h2>
      <form className="cavitybalance__form">
        <div className="cavitybalance__form--inputgroup">
          <span>No. Rows</span>
          <input
            type="number"
            placeholder="5"
            id="nRows"
            onChange={handleNumberofRows}
          />
          <button
            className="btn btn-blue btn-left"
            type="button"
            onClick={addRows}
          >
            Add Rows
          </button>
          <button
            className="btn btn-red btn-right"
            type="button"
            onClick={deleteAllRows}
          >
            Delete All Rows
          </button>
        </div>
        <div className="cavitybalance__form--inputgroup">
          <button
            className="btn btn-blue btn-left"
            type="button"
            onClick={addRow}
          >
            Add Row
          </button>
          <button
            className="btn btn-red btn-right"
            type="button"
            onClick={deleteLastRow}
          >
            Delete Last Row
          </button>

          <button
            className="btn btn-blue btn-left"
            type="button"
            onClick={addColumn}
          >
            Add New Column
          </button>
          <button className="btn btn-red btn-right" type="button">
            Delete Column
          </button>
        </div>
        <h3 className="cavitybalance__label">Input Data</h3>
        <div className="table-wrapper cavitybalance__table">
          <HotTable
            licenseKey="non-commercial-and-evaluation"
            colHeaders={true}
            rowHeaders={true}
            contextMenu={true}
            data={dataset}
          >
            {columns}
          </HotTable>
        </div>
        <button className="btn btn-calculate" type="button">
          Calculate
        </button>
        <div className="cavitybalance__chart">
          <Line
            data={chartData}
            options={chartOptions}
            width="400"
            height="400"
          />
        </div>
      </form>
    </div>
  );
};
