// src/app/components/mainmenu/viscosity-curve/viscosity-curve.component.ts
import { stringify } from '@angular/compiler/src/util';
import { Component, OnInit, ViewChild } from '@angular/core';
import { HotTableComponent } from '@handsontable/angular';
import { ChangethemeService } from 'src/app/services/changetheme.service';
import { SidebarService } from 'src/app/services/sidebar.service';

@Component({
  selector: 'app-viscosity-curve',
  templateUrl: './viscosity-curve.component.html',
  styleUrls: ['./viscosity-curve.component.css']
})
export class ViscosityCurveComponent implements OnInit {

  isOpen = false;
  isLight = true;

  @ViewChild("hot") hot: HotTableComponent;

  dataset: any[] = [
    {InjectionSpeed: 0.3, FillTime: 12.17, InjectionPressure: 2635, PlasticPressure: 0, ShearRate: 0, Viscosity: 0, percentageVariation: 0},
    {InjectionSpeed: 0.6, FillTime: 6.13, InjectionPressure: 2970, PlasticPressure: 0, ShearRate: 0, Viscosity: 0, percentageVariation: 0},
    {InjectionSpeed: 0.9, FillTime: 4.11, InjectionPressure: 2845, PlasticPressure: 0, ShearRate: 0, Viscosity: 0, percentageVariation: 0},
    {InjectionSpeed: 1.2, FillTime: 3.1, InjectionPressure: 0, PlasticPressure: 0, ShearRate: 0, Viscosity: 0, percentageVariation: 0},
    {InjectionSpeed: 0, FillTime: 0, InjectionPressure: 0, PlasticPressure: 0, ShearRate: 0, Viscosity: 0, percentageVariation: 0},
    {InjectionSpeed: 0, FillTime: 0, InjectionPressure: 0, PlasticPressure: 0, ShearRate: 0, Viscosity: 0, percentageVariation: 0},
    {InjectionSpeed: 0, FillTime: 0, InjectionPressure: 0, PlasticPressure: 0, ShearRate: 0, Viscosity: 0, percentageVariation: 0},
    {InjectionSpeed: 0, FillTime: 0, InjectionPressure: 0, PlasticPressure: 0, ShearRate: 0, Viscosity: 0, percentageVariation: 0},
    {InjectionSpeed: 0, FillTime: 0, InjectionPressure: 0, PlasticPressure: 0, ShearRate: 0, Viscosity: 0, percentageVariation: 0},
    {InjectionSpeed: 0, FillTime: 0, InjectionPressure: 0, PlasticPressure: 0, ShearRate: 0, Viscosity: 0, percentageVariation: 0}
  ];

  constructor(
    private sidebarService: SidebarService,
    public changeThemeService: ChangethemeService
  ) {

  }

  ngOnInit(): void {
    this.sidebarService.change.subscribe((isOpen: boolean)=> {
      this.isOpen = isOpen;
    });
    this.changeThemeService.change.subscribe((isLight: boolean)=> {
      this.isLight = isLight;
    });
  }

  addRows(numberOfRows: number){
    for(var _i = 0; _i < numberOfRows; _i++){
      this.dataset.push({InjectionSpeed: 0, FillTime: 0, InjectionPressure: 0, PlasticPressure: 0, ShearRate: 0, Viscosity: 0, percentageVariation: 0});
    }
    this.hot.updateHotTable({ data: this.dataset });
  }

  addIncrementalRows(initialValue: number, stepValue: number, timesValue: number){
    var number=  initialValue;
    for(var _i = 0; _i < timesValue; _i++){
      this.dataset.push({InjectionSpeed: number, FillTime: 0, InjectionPressure: 0, PlasticPressure: 0, ShearRate: 0, Viscosity: 0, percentageVariation: 0});
      number += stepValue;
    }
    this.hot.updateHotTable({ data: this.dataset });
  }

  deleteRows(){
    this.dataset = [];
    this.hot.updateHotTable({ data: this.dataset });
  }

  calculate(intensificationRatio: number) {
    var previousViscosity = 0;
    this.dataset.forEach(element => {
      element["PlasticPressure"] = intensificationRatio * element["InjectionPressure"];
      element["ShearRate"] = 1 / element["FillTime"];
      element["Viscosity"] = element["FillTime"] * element["PlasticPressure"];
      element["percentageVariation"] = (element["Viscosity"] - previousViscosity)/previousViscosity;
      previousViscosity = element["Viscosity"];
    });
    this.hot.updateHotTable({ data: this.dataset });
  }

}

<div
  class="wrapper"
  [ngStyle]="{ 'margin-left': this.isOpen ? '250px' : '82px' }"
  [ngClass]="{ light: this.isLight, dark: !this.isLight }"
>
  <div class="row">
    <div class="col-6 col-m-12 col-sm-12">
      <div class="counter bg-primary">
        <p>
          <i class="fas fa-arrow-up"></i>
        </p>
        <h3>Intensification Ratio</h3>
        <input type="number" value="1.5411" required #intensificationRatio />
      </div>
    </div>

    <div class="col-6 col-m-12 col-sm-12">
      <div class="counter bg-primary">
        <p>
          <input type="number" value="1" #numberOfRows />
          <button (click)="addRows(numberOfRows.value)">Add Row (s)</button>
          <button class="danger" (click)="deleteRows()">Delete Rows</button>
        </p>

        <h3>Incremental</h3>
        <p>
          From <input type="number" value="0.3" #initial /> By
          <input type="number" value="0.3" #step />
        </p>
        <p><input type="number" value="5" #times /> Times</p>
        <button
          (click)="
            addIncrementalRows(+initial.value, +step.value, +times.value)
          "
        >
          Add Rows
        </button>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12 col-m-12 col-sm-12">
      <div class="card">
        <div class="card-header">
          <h3>Input Table</h3>
        </div>
        <div class="card-content">
          <hot-table
            class="table"
            licenseKey="non-commercial-and-evaluation"
            [colHeaders]="true"
            [rowHeaders]="true"
            [contextMenu]="true"
            [data]="dataset"
            #hot
          >
            <hot-column
              data="InjectionSpeed"
              title="Injection Speed"
            ></hot-column>
            <hot-column data="FillTime" title="Fill Time"></hot-column>
            <hot-column
              data="InjectionPressure"
              title="Injection Pressure"
            ></hot-column>
            <hot-column
              data="PlasticPressure"
              [readOnly]="true"
              title="Plastic Pressure"
            ></hot-column>
            <hot-column
              data="ShearRate"
              [readOnly]="true"
              title="Shear Rate"
            ></hot-column>
            <hot-column
              data="Viscosity"
              [readOnly]="true"
              title="Viscosity"
            ></hot-column>
            <hot-column
              data="percentageVariation"
              [readOnly]="true"
              title="%Variation"
            ></hot-column>
          </hot-table>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12 col-m-12 col-sm-12">
      <div class="counter counter-btn bg-success" (click)="calculate(+intensificationRatio.value)">
        <button class="button-success">
          <i class="fas fa-calculator"> Calculate</i>
        </button>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12 col-m-12 col-sm-12">
      <div class="card">
        <div class="card-header">
          <h3>Chartjs</h3>
        </div>
        <div class="card-content">
          <canvas id="myChart"></canvas>
        </div>
      </div>
    </div>
  </div>
</div>

// src/Pages/ViscosityCurve/ViscosityCurve.jsx
import "./ViscosityCurve.scss";
import "handsontable/dist/handsontable.min.css";
import { useState, useReducer } from "react";
import { HotTable, HotColumn } from "@handsontable/react";
import { Line } from "react-chartjs-2";

import {
  defaultDataset,
  defaultChartdata,
  dataRow,
} from "./viscositycurve-dataset";
import chartOptions from "../chartoptions";

let dataset = defaultDataset;

let chartData = defaultChartdata;

let viscosityData = [0];
let injectionSpeedData = [0];

function ViscosityCurve() {
  const [intensificationRatio, setIntensificationRatio] = useState(11.45);
  const [numberOfRows, setNumberOfRows] = useState(0);
  const [, forceUpdate] = useReducer((x) => x + 1, 0);

  const updateChart = () => {
    viscosityData = dataset.map((element) => element["Viscosity"]);
    injectionSpeedData = dataset.map((element) => element["InjectionSpeed"]);
    chartData = {
      labels: injectionSpeedData,
      datasets: [
        {
          label: "Viscosity",
          data: viscosityData,
          fill: false,
          backgroundColor: "rgb(0, 0, 0)",
          borderColor: "rgba(255, 99, 132, 0.2)",
        },
      ],
    };
  };

  const addRow = () => {
    dataset.push(dataRow);
    forceUpdate();
  };

  const addRows = () => {
    for (let index = 0; index < numberOfRows; index++) {
      dataset.push(dataRow);
    }
    forceUpdate();
  };

  const deletLastRow = () => {
    dataset.splice(-1, 1);
    forceUpdate();
  };

  const deleteAllRows = () => {
    dataset = [dataRow];
    forceUpdate();
  };

  const calculate = (e) => {
    let previousViscosity = 0;
    dataset.forEach((element) => {
      element["PlasticPressure"] =
        element["InjectionPressure"] * intensificationRatio;
      element["ShearRate"] = 1 / element["FillTime"];
      element["Viscosity"] = element["FillTime"] * element["PlasticPressure"];
      element["percentageVariation"] =
        (element["Viscosity"] - previousViscosity) / previousViscosity;
      previousViscosity = element["Viscosity"];
    });
    updateChart();
    forceUpdate();
  };

  const handleIntensificationRatioChange = (event) => {
    setIntensificationRatio(event.target.value);
    calculate();
  };

  const handleNumberRows = (event) => {
    if (event.target.value > 0) {
      setNumberOfRows(event.target.value);
    }
  };

  return (
    <div className="viscositycurve">
      <h2 className="study-title">Viscosity Curve</h2>
      <form className="viscositycurve__form">
        <div className="viscositycurve__form--intensificationratio">
          <label className="viscositycurve__form--intensificationratio-label">
            Intensification Ratio
          </label>
          <input
            className="viscositycurve__form--intensificationratio-input"
            type="number"
            value={intensificationRatio}
            onChange={handleIntensificationRatioChange}
          />
        </div>
        <div className="viscositycurve__form--inputdata">
          <h3 className="viscositycurve__form--h3">Input Data</h3>
          <div className="viscositycurve__form--inputgroup">
            <span>No. Rows</span>
            <input
              type="number"
              placeholder="5"
              id="nRows"
              onChange={handleNumberRows}
            />
            <button
              className="btn btn-blue btn-left"
              type="button"
              onClick={addRows}
            >
              Add Rows
            </button>
            <button
              className="btn btn-red btn-right"
              type="button"
              onClick={deleteAllRows}
            >
              Delete All Rows
            </button>
          </div>
          <div className="viscositycurve__form--inputgroup">
            <button
              className="btn btn-blue btn-left"
              type="button"
              onClick={addRow}
            >
              Add Row
            </button>
            <button
              className="btn btn-red btn-right"
              type="button"
              onClick={deletLastRow}
            >
              Delete Last Row
            </button>
          </div>

          <button
            className="btn btn-calculate"
            onClick={(e) => {
              calculate(e);
            }}
            type="button"
          >
            Calculate
          </button>
          <div className="table-wrapper viscositycurve__table">
            <HotTable
              licenseKey="non-commercial-and-evaluation"
              colHeaders={true}
              rowHeaders={true}
              contextMenu={true}
              data={dataset}
            >
              <HotColumn data="InjectionSpeed" title="Injection Speed" />
              <HotColumn data="FillTime" title="Fill Time" />
              <HotColumn data="InjectionPressure" title="Injection Pressure" />
              <HotColumn
                data="PlasticPressure"
                title="Plastic Pressure"
                readOnly={true}
              />
              <HotColumn data="ShearRate" title="Shear Rate" readOnly={true} />
              <HotColumn data="Viscosity" title="Viscosity" readOnly={true} />
              <HotColumn
                data="percentageVariation"
                title="% Variation"
                readOnly={true}
              />
            </HotTable>
          </div>
        </div>
      </form>
      <div className="viscositycurve__chart">
        <Line
          data={chartData}
          options={chartOptions}
          width="90vw"
          height="90vh"
        />
      </div>
    </div>
  );
}

export default ViscosityCurve;
