// src/app/components/viscosity-curve/viscosity-curve.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { HotTableComponent } from '@handsontable/angular';
import { ChartDataSets, ChartOptions, ChartType } from 'chart.js';
import { BaseChartDirective, Color, Label } from 'ng2-charts';

@Component({
  selector: 'app-viscosity-curve',
  templateUrl: './viscosity-curve.component.html',
  styleUrls: ['./viscosity-curve.component.css'],
})
export class ViscosityCurveComponent implements OnInit {
  dataset: any[] = [
    {
      InjectionSpeed: 0.3,
      FillTime: 3.65,
      InjectionPressure: 875,
      PlasticPressure: 0,
      ShearRate: 0,
      Viscosity: 0,
      percentageVariation: 0,
    },
    {
      InjectionSpeed: 0.6,
      FillTime: 1.81,
      InjectionPressure: 1015,
      PlasticPressure: 0,
      ShearRate: 0,
      Viscosity: 0,
      percentageVariation: 0,
    },
    {
      InjectionSpeed: 0.9,
      FillTime: 0.95,
      InjectionPressure: 1365,
      PlasticPressure: 0,
      ShearRate: 0,
      Viscosity: 0,
      percentageVariation: 0,
    },
    {
      InjectionSpeed: 1.2,
      FillTime: 0.72,
      InjectionPressure: 1514,
      PlasticPressure: 0,
      ShearRate: 0,
      Viscosity: 0,
      percentageVariation: 0,
    },
    {
      InjectionSpeed: 1.5,
      FillTime: 0.58,
      InjectionPressure: 1685,
      PlasticPressure: 0,
      ShearRate: 0,
      Viscosity: 0,
      percentageVariation: 0,
    },
    {
      InjectionSpeed: 1.8,
      FillTime: 0.45,
      InjectionPressure: 1758,
      PlasticPressure: 0,
      ShearRate: 0,
      Viscosity: 0,
      percentageVariation: 0,
    },
    {
      InjectionSpeed: 2.1,
      FillTime: 0.3,
      InjectionPressure: 1824,
      PlasticPressure: 0,
      ShearRate: 0,
      Viscosity: 0,
      percentageVariation: 0,
    },
    {
      InjectionSpeed: 2.4,
      FillTime: 0.25,
      InjectionPressure: 1875,
      PlasticPressure: 0,
      ShearRate: 0,
      Viscosity: 0,
      percentageVariation: 0,
    },
    {
      InjectionSpeed: 2.7,
      FillTime: 0.22,
      InjectionPressure: 1908,
      PlasticPressure: 0,
      ShearRate: 0,
      Viscosity: 0,
      percentageVariation: 0,
    },
    {
      InjectionSpeed: 3,
      FillTime: 0.21,
      InjectionPressure: 1925,
      PlasticPressure: 0,
      ShearRate: 0,
      Viscosity: 0,
      percentageVariation: 0,
    },
  ];

  viscosityData: Array<number> = [0];
  injectionSpeedData: Array<number> = [0];

  public lineChartData: ChartDataSets[] = [{ data: [0], label: 'Viscosity' }];
  public lineChartLabels: Label[] = ['0'];
  public lineChartOptions: ChartOptions = {
    responsive: true,
    scales: {
      // We use this empty structure as a placeholder for dynamic theming.
      xAxes: [{}],
      yAxes: [
        {
          id: 'y-axis-0',
          position: 'left',
        },
        {
          id: 'y-axis-1',
          position: 'right',
          gridLines: {
            color: 'rgba(255,0,0,0.3)',
          },
          ticks: {
            fontColor: 'red',
          },
        },
      ],
    },
  };
  public lineChartColors: Color[] = [
    {
      // red
      backgroundColor: 'rgba(255,0,0,0.3)',
      borderColor: 'red',
      pointBackgroundColor: 'rgba(148,159,177,1)',
      pointBorderColor: '#fff',
      pointHoverBackgroundColor: '#fff',
      pointHoverBorderColor: 'rgba(148,159,177,0.8)',
    },
  ];
  public lineChartLegend = true;
  public lineChartType: ChartType = 'line';

  @ViewChild('hot', { static: false })
  hot!: HotTableComponent;
  @ViewChild(BaseChartDirective, { static: true })
  chart!: BaseChartDirective;

  constructor() {}

  ngOnInit(): void {}

  addRow() {
    this.dataset.push({
      InjectionSpeed: 0,
      FillTime: 0,
      InjectionPressure: 0,
      PlasticPressure: 0,
      ShearRate: 0,
      Viscosity: 0,
      percentageVariation: 0,
    });
    this.hot.updateHotTable({ data: this.dataset });
  }

  addRows(numberRows: number) {
    console.log(numberRows);
    for (var i = 0; i < numberRows; i++) {
      this.dataset.push({
        InjectionSpeed: 0,
        FillTime: 0,
        InjectionPressure: 0,
        PlasticPressure: 0,
        ShearRate: 0,
        Viscosity: 0,
        percentageVariation: 0,
      });
    }
    this.hot.updateHotTable({ data: this.dataset });
  }

  deleteLastRow() {
    this.dataset.splice(-1, 1);
    this.hot.updateHotTable({ data: this.dataset });
  }

  deleteAllRows() {
    this.dataset = [
      {
        InjectionSpeed: 0,
        FillTime: 0,
        InjectionPressure: 0,
        PlasticPressure: 0,
        ShearRate: 0,
        Viscosity: 0,
        percentageVariation: 0,
      },
    ];
    this.hot.updateHotTable({ data: this.dataset });
  }

  calculate(intensificationRatio: number) {
    var previousViscosity = 0;
    this.dataset.forEach((element) => {
      element['PlasticPressure'] =
        element['InjectionPressure'] * intensificationRatio;
      element['ShearRate'] = 1 / element['FillTime'];
      element['Viscosity'] = element['FillTime'] * element['PlasticPressure'];
      element['percentageVariation'] =
        (element['Viscosity'] - previousViscosity) / previousViscosity;
      previousViscosity = element['Viscosity'];
    });
    this.hot.updateHotTable({ data: this.dataset });
    this.updateChart();
  }

  private updateChart() {
    this.viscosityData = this.dataset.map((element) => element['Viscosity']);
    this.injectionSpeedData = this.dataset.map(
      (element) => element['InjectionSpeed']
    );
    this.lineChartData = [{ data: this.viscosityData, label: 'Viscosity' }];
    this.lineChartLabels = this.injectionSpeedData.map(String);
    this.chart.update();
  }
}

<app-study-title name="Viscosity Curve"></app-study-title>

<div class="mb-3">
  <label for="intensificationRatio" class="form-label">
    <i class="fas fa-arrow-up"></i> Intensification Ratio</label
  >
  <input
    type="number"
    step="any"
    class="form-control"
    value="11.45"
    required
    #intensificationRatio
  />
</div>

<div class="mb-3">
  <h4>Input Data</h4>
  <div class="input-group mb-2">
    <div class="input-group-prepend">
      <span class="input-group-text">No. Rows</span>
    </div>
    <input type="number" class="form-control" placeholder="10" #noRows />
    <button
      type="button"
      class="btn btn-primary"
      (click)="addRows(+noRows.value)"
    >
      Add Rows
    </button>
    <button type="button" class="btn btn-danger" (click)="deleteAllRows()">
      Delete All Rows
    </button>
  </div>
  <div class="btn-group mx-2 mb-2" role="rows-group">
    <button type="button" class="btn btn-primary" (click)="addRow()">
      Add Row
    </button>
    <button type="button" class="btn btn-danger" (click)="deleteLastRow()">
      Delete Last Row
    </button>
  </div>
  <div class="wrapper">
    <hot-table
      licenseKey="non-commercial-and-evaluation"
      [colHeaders]="true"
      [rowHeaders]="true"
      [contextMenu]="true"
      [data]="dataset"
      #hot
    >
      <hot-column data="InjectionSpeed" title="Injection Speed"></hot-column>
      <hot-column data="FillTime" title="Fill Time"></hot-column>
      <hot-column
        data="InjectionPressure"
        title="Injection Pressure"
      ></hot-column>
      <hot-column
        data="PlasticPressure"
        [readOnly]="true"
        title="Plastic Pressure"
      ></hot-column>
      <hot-column
        data="ShearRate"
        [readOnly]="true"
        title="Shear Rate"
      ></hot-column>
      <hot-column
        data="Viscosity"
        [readOnly]="true"
        title="Viscosity"
      ></hot-column>
      <hot-column
        data="percentageVariation"
        [readOnly]="true"
        title="%Variation"
      ></hot-column>
    </hot-table>
  </div>
</div>

<div class="mb-3">
  <div class="d-grid gap-2">
    <button
      type="button"
      class="btn btn-success"
      (click)="calculate(+intensificationRatio.value)"
    >
      Calculate
    </button>
  </div>
</div>

<div class="mb-3">
  <div class="chart-container">
    <canvas
      baseChart
      width="400"
      height="400"
      [datasets]="lineChartData"
      [labels]="lineChartLabels"
      [options]="lineChartOptions"
      [colors]="lineChartColors"
      [legend]="lineChartLegend"
      [chartType]="lineChartType"
    ></canvas>
  </div>
</div>

// src/Pages/ViscosityCurve/ViscosityCurve.jsx
import "./ViscosityCurve.scss";
import "handsontable/dist/handsontable.min.css";
import { useState, useReducer } from "react";
import { HotTable, HotColumn } from "@handsontable/react";
import { Line } from "react-chartjs-2";

import {
  defaultDataset,
  defaultChartdata,
  dataRow,
} from "./viscositycurve-dataset";
import chartOptions from "../chartoptions";

let dataset = defaultDataset;

let chartData = defaultChartdata;

let viscosityData = [0];
let injectionSpeedData = [0];

function ViscosityCurve() {
  const [intensificationRatio, setIntensificationRatio] = useState(11.45);
  const [numberOfRows, setNumberOfRows] = useState(0);
  const [, forceUpdate] = useReducer((x) => x + 1, 0);

  const updateChart = () => {
    viscosityData = dataset.map((element) => element["Viscosity"]);
    injectionSpeedData = dataset.map((element) => element["InjectionSpeed"]);
    chartData = {
      labels: injectionSpeedData,
      datasets: [
        {
          label: "Viscosity",
          data: viscosityData,
          fill: false,
          backgroundColor: "rgb(0, 0, 0)",
          borderColor: "rgba(255, 99, 132, 0.2)",
        },
      ],
    };
  };

  const addRow = () => {
    dataset.push(dataRow);
    forceUpdate();
  };

  const addRows = () => {
    for (let index = 0; index < numberOfRows; index++) {
      dataset.push(dataRow);
    }
    forceUpdate();
  };

  const deletLastRow = () => {
    dataset.splice(-1, 1);
    forceUpdate();
  };

  const deleteAllRows = () => {
    dataset = [dataRow];
    forceUpdate();
  };

  const calculate = (e) => {
    let previousViscosity = 0;
    dataset.forEach((element) => {
      element["PlasticPressure"] =
        element["InjectionPressure"] * intensificationRatio;
      element["ShearRate"] = 1 / element["FillTime"];
      element["Viscosity"] = element["FillTime"] * element["PlasticPressure"];
      element["percentageVariation"] =
        (element["Viscosity"] - previousViscosity) / previousViscosity;
      previousViscosity = element["Viscosity"];
    });
    updateChart();
    forceUpdate();
  };

  const handleIntensificationRatioChange = (event) => {
    setIntensificationRatio(event.target.value);
    calculate();
  };

  const handleNumberRows = (event) => {
    if (event.target.value > 0) {
      setNumberOfRows(event.target.value);
    }
  };

  return (
    <div className="viscositycurve">
      <h2 className="study-title">Viscosity Curve</h2>
      <form className="viscositycurve__form">
        <div className="viscositycurve__form--intensificationratio">
          <label className="viscositycurve__form--intensificationratio-label">
            Intensification Ratio
          </label>
          <input
            className="viscositycurve__form--intensificationratio-input"
            type="number"
            value={intensificationRatio}
            onChange={handleIntensificationRatioChange}
          />
        </div>
        <div className="viscositycurve__form--inputdata">
          <h3 className="viscositycurve__form--h3">Input Data</h3>
          <div className="viscositycurve__form--inputgroup">
            <span>No. Rows</span>
            <input
              type="number"
              placeholder="5"
              id="nRows"
              onChange={handleNumberRows}
            />
            <button
              className="btn btn-blue btn-left"
              type="button"
              onClick={addRows}
            >
              Add Rows
            </button>
            <button
              className="btn btn-red btn-right"
              type="button"
              onClick={deleteAllRows}
            >
              Delete All Rows
            </button>
          </div>
          <div className="viscositycurve__form--inputgroup">
            <button
              className="btn btn-blue btn-left"
              type="button"
              onClick={addRow}
            >
              Add Row
            </button>
            <button
              className="btn btn-red btn-right"
              type="button"
              onClick={deletLastRow}
            >
              Delete Last Row
            </button>
          </div>

          <button
            className="btn btn-calculate"
            onClick={(e) => {
              calculate(e);
            }}
            type="button"
          >
            Calculate
          </button>
          <div className="table-wrapper viscositycurve__table">
            <HotTable
              licenseKey="non-commercial-and-evaluation"
              colHeaders={true}
              rowHeaders={true}
              contextMenu={true}
              data={dataset}
            >
              <HotColumn data="InjectionSpeed" title="Injection Speed" />
              <HotColumn data="FillTime" title="Fill Time" />
              <HotColumn data="InjectionPressure" title="Injection Pressure" />
              <HotColumn
                data="PlasticPressure"
                title="Plastic Pressure"
                readOnly={true}
              />
              <HotColumn data="ShearRate" title="Shear Rate" readOnly={true} />
              <HotColumn data="Viscosity" title="Viscosity" readOnly={true} />
              <HotColumn
                data="percentageVariation"
                title="% Variation"
                readOnly={true}
              />
            </HotTable>
          </div>
        </div>
      </form>
      <div className="viscositycurve__chart">
        <Line
          data={chartData}
          options={chartOptions}
          width="90vw"
          height="90vh"
        />
      </div>
    </div>
  );
}

export default ViscosityCurve;
